# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-11-12 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Bracelets', 'Bracelets'), ('Necklaces', 'Necklaces'), ('Earings', 'Earings'), ('WeddingBands', 'WeddingBands'), ('WhiteDiamondsRings', 'WhiteDiamondsRings'), ('ColouredDiamondsRings', 'ColouredDiamondsRings')], default='', max_length=50)),
                ('name', models.CharField(default='', max_length=254)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=3, max_digits=6)),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
